version: '3'

services:

  web-ui:
        image: vendor/web-ui
        ports:
            - 8080:8080
        labels:
            project.git: "https://github.com/laravel/quickstart-basic.git"
            project.build: make
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8080:8080"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
  php:
   image: chialab/php:7.3-fpm
    volumes:
      - ./public:/src
      - .:/app/
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
  mysql:
    image: mariadb
    container_name: ${APP_NAME}-mysql
    command: --lower_case_table_names=2
    volumes:
       - './data/db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
    ports:
      - '3306:3306'
      
networks:
  wpsite:
volumes:
  db_data:
